sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.0
      env: COMPOSER_ARGUMENTS="--prefer-lowest --prefer-stable"
    - php: 7.0
    - php: 7.1
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_script:
  - composer update --prefer-dist ${COMPOSER_ARGUMENTS}

script:
  - |
    if [[ "${TRAVIS_PHP_VERSION}" == "hhvm" ]]; then
      hhvm --version
      echo "hhvm.php7.all=1" >> /etc/hhvm/php.ini
    fi
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover=coverage.clover
  - |
    if [[ "${TRAVIS_PHP_VERSION}" == "7.1" ]]; then
      vendor/bin/docheader check library tests
    fi

after_script:
  - |
    if [[ "${TRAVIS_PHP_VERSION}" == "7.1" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
